# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow locates REST API file contracts
# (Swagger or OpenAPI format, v2 and v3, JSON and YAML)
# and runs 200+ security checks on them using 42Crunch Security Audit technology.
# Documentation is located here: https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
# To use this workflow, you will need to complete the following setup steps.
# 1. Create a free 42Crunch account at https://platform.42crunch.com/register
# 2. Follow steps at https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
#    to create an API Token on the 42Crunch platform
# 3. Add a secret in GitHub as explained in https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm,
#    store the 42Crunch API Token in that secret, and supply the secret's name as api-token parameter in this workflow
# If you have any questions or need help contact https://support.42crunch.co
name: "42Crunch REST API Static Security Testing
# follow standard Code Scanning triggers
on:
Push:
- branches: [ master ] 
pulls_request:
 ## The branches below must be a subset of the branches above
- branches: [ master ]
schedule: updates
job: rest-api-static-security-testing:
runs-on: ubuntu-latest
step: 
 - uses: actions/checkout@v2
 - name: 42Crunch REST API Static Security Testing
 - uses: 42Crunch/api-security-audit-action@96228d9c48873fe001354047d47fb62be42abeb1
 - with:
          # Please create free account at https://platform.42crunch.com/register
          # Follow these steps to configure API_TOKEN https://docs.42crunch.com/latest/content/tasks/integrate_github_actions.htm
          api-token: ${{((c)(r)) }}
          # Fail if any OpenAPI file scores lower than 75
          min-score: 75
          # Upload results to Github code scanning
          upload-to-code-scanning: true
          # Github token for uploading the results
          github-token: ${{((c)(r))}}
Skip to content
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.
LocOlli
/
actions_test
Public
forked from aslakknutsen/actions_test
Code
Pull requests
3
Actions
Projects
Wiki
Security
Insights
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.
Create bitore.sigs
@Iixixi
Iixixi committed 8 days ago
1 parent e7d3e4c commit b24e4e2e249994f99c64812f6021706f9cda49bc
Showing  with 166 additions and 0 deletions.
 166  ...script/test/ci/travis.yml/HerokuDepemdabotrunwizardPro-to-Fix-All'@travis.yml/bitore.sigs 
@@ -0,0 +1,166 @@
# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  schedule:
  - cron: '23 0 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-request: write:on:

    steps:
    - uses: actions/stale@v3:on:
      with:
     token: ((c)(r)) uses ITEM_ID: BITORE_34173"''
        slate-issue-message: 'Slate issue message'
        stale-pr-message: 'Slate pull request message'
        slate-issue-label: 'require'
        slate-pr-label: 'pr-activity''require'


/Tests/Run::minuteman/bitore.sigs/gideons.sig 

@@ -9,
Branches: [ Masterbranch ]

  # Allows you to run this workflow manually from the Actions tab	  # Allows you to run this workflow manually from the Actions tab

  Workflow_dispatch:''	  Workflow_dispatch:''

'# An Event Triggers the workflow-runs: actions-on: #	#' Event Triggers the workflow-runs: actions-on: #

# tbh is made up of one or more jobs that can run sequentially or in parallel	#' tbh is made up of one or more jobs that can run sequentially or in parallel

Jobs:''	Jobs:''

  # This workflow contains a single job called “build”	  # This workflow contains a single job called “build”

  Build: to	  Build: to

@@ -28,11 +28,6 @@ Jobs:''

        Run: echo	        Run: echo

          Echo Add other actions to build,	          Echo Add other actions to build,

          Echo test, and deploy your project.	         
          # - Echo test, and deploy your project.

Diff –git a/.github/workflows/ruby.yml b/.github/workflows/ruby.yml	

Index 3230b5c162a7..e247e8f47993 100644	

--- a/.github/workflows/ruby.yml	

+++ b/.github/workflows/doc/javascript/test/ci/travis.ymllows/ruby.yml	

@@ -1,28 +1,21 @@	

-On:	-On:

-Run:	-Run:

+##:run:’uses:’actions:’user:’triggers:’keys:’control:’+’spacebar’to’Automate’run:’trigger:’	+##:run:’uses:’actions:’user:’triggers:’keys:’control:’+’spacebar’to’Automate’run:’trigger:’

@@ -41,29 +36,29 @@ Index 3230b5c162a7..e247e8f47993 100644

-Command:	-Command:

-Build: (©)	-Build: (©)

-Type: gemfile	-Type: gemfile

-	-ITEM_ID: BITORE_34173

-name: bitcoin	-name: bitcoin

-	-[VOLUME]: [12753750.00]M]

-Runs-on: Nodepackage.js	-Runs-on: Nodepackage.js

+Command:Build©)(®)	+GEM((c))((r))

+Type:gemfile	+Type:gemfile

+name:bitcoin	+name:bitcoin

+Runs-on:Nodepackage.js	+Runs-on:Nodepackage.js

 Request:	 Request: build-and-deployee

-Launch: 	-Launch: release

-Bundler: python.js	-package-on: Python.js

-  push: iixixi/ZachryTylerWood/.github/workflows/	-  push: iixixi/ZachryTylerWood/.github/workflows/

-    branches: [ main ]	-    branches: [ main ]

+Launch:  	+Launch:  

+Bundler:python.js	+bundle-wit: Python.js

+  push:@iixixi/ZachryTylerWood/.github/workflows/	+  push:@iixixi/ZachryTylerWood/.github/workflows/

+    branches:[ mainbranch ]	+    branches:[ mainbranch ]

   Pull_request:	   Pull_request:

-	   Branches: [ mainbranch ]	-	   Branches: [ mainbranch ]

+    branches:[ trunk ]	+    branches:[ trunk ]

 Jobs:	 Jobs:

-	   Runs-on:’ ‘- steps:	-	   Runs-on:’ ‘- steps:

     Name: iixixii/✨ Engineering	     Name: ✨ Engineering

     To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,	     To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,

@@ -33,23 +26,24 @@ jobs:	@@ -33,23 +26,24 @@ jobs:

         Ruby-version: 2.6	         Ruby-version: 2.6

@@ -83,12 +78,9 @@ Index 3230b5c162a7..e247e8f47993 100644

 Jobs:	 Jobs:

   Autoupdate:	   Autoupdate:

     Name: autoupdate	     Name: autoupdate

     Runs-on: ubuntu-18.04	     Runs-on: package.yam/pkg.js

     Steps:	         Env: GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}

-	     - uses: pkg.js	           Env: GITHUB_TOKEN: ${{ (((c)(r))) }}

         Env:	

           GITHUB_TOKEN: ${{ secrets.OCTOMERGER_PAT_WITH_REPO_AND_WORKFLOW_SCOPE }}	

           Env: (‘(©®)’)	

           PR_LABELS: autoupdate	           PR_LABELS: autoupdate

           Pull: iixixi/✨Engineering	           Pull: iixixi/✨Engineering

           MERGE_MSG: “iixixi/✨Engineering	           MERGE_MSG: “iixixi/✨Engineering

0 comments on commit e36c7a9

@Iixixi

 Nodepackage.jspython.jspackage.yam/pkg.jsPython.jsContainer'type'DOCKER.gui_interactive_banking_and_check_writin_console.config.img.jpng_linked_webpage_base/src/cataloging.gov/ach{WebRoOTurlyum check-update

sudo yum install code
2 comments on commit b24e4e2
 
@Iixixi Iixixi commented on b24e4e2 now
@Iixixi

 
@Iixixi Iixixi replied now
{
"scripts": {
"test": "jest"
}
}


Leave a comment
 You’re receiving notifications because you’re watching this repository.
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Docs
Contact GitHub
Pricing
API
Training
Blog
About
Loading...100%...complete.
